name: flutter_sidekick
description: Widgets for creating Hero-like animations between two widgets within the same screen
version: 0.1.3
homepage: https://github.com/letsar/flutter_sidekick

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
